name: Product Service CI #Just a name

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs: #What work should GitHub perform?
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source #checkout the code
        uses: actions/checkout@v4

      - name: Set up JDK 21 #install the jav
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Grant execute permission # make the gradlew executable
        run: chmod +x gradlew

      - name: Build + Test + Coverage
        run: ./gradlew clean build jacocoTestReport

      - name: Upload JaCoCo Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/html
      - name: sonar analysis
        run: ./gradlew sonar \
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
          -Dsonar.token=${{ secrets.SONAR_TOKEN }}
        
      - name: Build project #build the project
        run: ./gradlew build
